# This is a basic workflow to help you get started with Actions

name: deploy on pr update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]    
  pull_request:
    branches: [ feature ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare_variables:
    runs-on: ubuntu-20.04
    steps:
      - name: see if helm is available on gh actions
        run: |
          helm version
  #build:
    # The type of runner that the job will run on
    #runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    #steps:
    #- uses: actions/checkout@master
    #- uses: keijoraamat/kubectl_action@main
      #id: kubectl_command
      #env:
        #KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      #with:
        #args: kubectl get pods --namespace test-auction
